### ISSUE TITLE
error when `gulp bundle`

### ISSUE THREAD

**Issue by johnandblue** [jrutter/Contentful-WYSIWYG-Editor#1]
Hello @jrutter  I was following all the steps that you recommend from your blog: http://www.onerutter.com/cms/how-to-create-a-contentful-ui-extension.html

but when I do `gulp bundle` to create the build the editor it throws this errors:
<img width="1329" alt="screen shot 2017-10-18 at 20 07 45" src="https://user-images.githubusercontent.com/21159524/31748326-5d307ba0-b440-11e7-9f6b-38858e329ad6.png">

I know they look like something is missing, but I can't figure out what...

**Comment by TobiasKrogh** [comment]
@johnandblue @jrutter 
Did the same, got the same error, imho fixed within https://github.com/jrutter/Contentful-WYSIWYG-Editor/pull/2

Cheers

**Comment by johnandblue** [comment]
Hi @TobiasKrogh, thx for the fix on this issue,

I don't know either if @jrutter is maintaining the repo, but I would be interested in using it for a Contentful project. 
As far as I went, with your fix the extension is still not working, due to some other syntax errors:
- in the `index.html` the urls are missing the `https:`

```js
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css" />

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <link href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.css" rel="stylesheet">
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.js"></script>
```
- when creating the extension and updating it the syntax is also wrong:
`contentful-extension update --srcdoc ./dist/index.min.html --force --space-id <space-id>`
`--srcdoc` is not a valid syntax, it should be `--src`

- Yet, if the bundled version where ok, it should be enough to put the `extension.json` in `./dist` modifying the source directly:
```js
{
  "id": "summerNoteEditor",
  "name": "Summernote WYSIWYG Editor",
  "src": "./index.min.html",
  "fieldTypes": ["Symbol", "Text"]
}
```
and create the extension from `./dist`:
```js
$ contentful-extension create --space-id $SPACE
```
And yet, I wasn't able to make it work... :(
Am I missing something else?

**Comment by johnandblue** [comment]
@TobiasKrogh @jrutter Replying to myself...
the last error was in the `extension.json`, to be correct it should look like this:
```
{
  "id": "summerNoteEditor",
  "name": "Summernote WYSIWYG Editor",
  "srcdoc": "./index.html",
  "fieldTypes": ["Symbol", "Text"]
}
```

and using this modify `index.html` it works for me on contentful, so you only need 2 files to upload the extension:

index.html:
```js
<!DOCTYPE html>
<html>
<head>
  <title>Summernote WYSIWYG</title>

  <link href="https://contentful.github.io/ui-extensions-sdk/cf-extension.css" rel="stylesheet">
  <script src="https://contentful.github.io/ui-extensions-sdk/cf-extension-api.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css" />

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.js"></script>

     <style>
         body {
           margin: 0;
           overflow: hidden;
         }
         .summernote {
           outline: 0;
           padding: 1em;
           margin-left: 3em;
           margin-top: -1px;
           margin-bottom: -1px;
           min-height: 30em;
         }
       </style>

</head>
<body>
  <div id="summernote"></div>
  <script>
  $(document).ready(function() {
       window.contentfulExtension.init(function (extension) {
       extension.window.startAutoResizer()

       var existingValue = extension.field.getValue();
       $('#summernote').html(existingValue);

       $('#summernote').summernote({
            height: 300, // set editor height
            minHeight: null, // set minimum height of editor
            maxHeight: null, // set maximum height of editor
            focus: true,
            toolbar: [
                 ['style', ['bold', 'italic', 'underline', 'clear']],
                 ['font', ['strikethrough']],
                 ['fontsize', ['fontsize']],
                 ['insert',['picture', 'link']],
                 ['color', ['color']],
                 ['para', ['ul', 'ol', 'paragraph', 'style']],
                 ['height', ['height']],
                 ['code',['codeview']]
            ],
      callbacks: {
        onInit: function() {
          console.log('Summernote is launched');
     },
        onChange: function(contents, $editable) {
             var markupStr = $(this).summernote('code');
             extension.field.setValue(markupStr);

        },
        onBlur: function() {
             var markupStr = $(this).summernote('code');
             extension.field.setValue(markupStr);
        }
       }
       });

  })

  });

  </script>
</body>
</html>

```

**Comment by TobiasKrogh** [comment]
@johnandblue 
So let us go through your points step by step :)

First the missing protocol in the index.html. That is totally fine. It is called protocol relative URL (great article on that topic - https://www.paulirish.com/2010/the-protocol-relative-url/). The URL in question will just use the protocol under which the current site was requested.

---

`contentful-extension update --srcdoc ./dist/index.min.html --force --space-id <space-id>`
There are two things to be considered here. The `srcdoc` param is valid (looking at https://github.com/contentful/contentful-extension-cli#extension-properties). But of course the `update` command only works once the extension was already created on the space.

So first command to be used:
`contentful-extension create --srcdoc ./dist/index.min.html --space-id <space-id>`

When making changes the update works with:
`contentful-extension update --srcdoc ./dist/index.min.html -force --space-id <space-id>`

The parameter `srcdoc` will overwrite the path in the extension.json when uploading the extension to contentful.

---

File reference for `index.html` / `index.min.html` / `dist/index.min.html`. It is actually the last one. BUT it will only be available after `gulp bundle` executes successfully.

To pick up from the README.md a better description might be:

#### Create the extension for the first time

```bash
$ gulp bundle
# creates `dist` directory and outputs index.min.html in there
$ contentful-extension create --srcdoc ./dist/index.min.html --space-id <space-id>
# uploads the extension to contentful
```

#### Update the extension

```bash
$ gulp bundle
# *updates* `dist` directory and outputs index.min.html in there
$ contentful-extension update --srcdoc ./dist/index.min.html --force --space-id <space-id>
# uploads the extension in contentful
```

As you pointed out: It is not needed to do so, but by using gulp, the `app.js` will be inlined into index.html (allowing developing them individually) also minifying JS and HTML code as there is a certain KB limit for the size of index.html. Also local testing is easier and there is no need to manually change the extension.json. I would think the author @jrutter wanted to keep the process as simple and convenient as possible. The README could need some more work though (no judging here @jrutter 😉 )

**Comment by jrutter** [comment]
Hi @johnandblue and @TobiasKrogh 
Thanks for the feedback, I have edited the readme as per your comments to make it more clear. Please let me know if you think anything else should be changed!
